services:
  keycloak:
    build:
      context: keycloak
      dockerfile: Dockerfile
    image: ghcr.io/heitor-galindo/keycloak:3.0.0
    command:
      - start-dev
      - --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      # Used when run the services out of docker
      #      KC_HOSTNAME: localhost
      #       Used when run the services with docker-compose
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_STRICT: false
      KC_LOG_LEVEL: INFO
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    restart: always

  eureka:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_DIR: EurekaServer
    image: ghcr.io/heitor-galindo/eureka:3.0.0
    ports:
      - "8761:8761"
    restart: on-failure

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_DIR: gateway
    image: ghcr.io/heitor-galindo/gateway:3.0.0
    environment:
      EUREKA_HOST: http://eureka:8761/eureka/
      KEYCLOAK_ISSUER: http://keycloak:8080/realms/MsSecurity
      SERVER_PORT: 8089
      SPRING_PROFILES_ACTIVE: docker
      LOG_LEVEL: INFO
      RESOURCE_ID: gateway
    ports:
      - "8089:8089"
    restart: on-failure

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_DIR: UserMS
    image: ghcr.io/heitor-galindo/user-service:4.0.0
    environment:
      EUREKA_HOST: http://eureka:8761/eureka/
      KEYCLOAK_ISSUER: http://keycloak:8080/realms/MsSecurity
      KEYCLOAK_TOKEN_URI: http://keycloak:8080/realms/MsSecurity/protocol/openid-connect/token
      KEYCLOAK_ADDRESS: http://keycloak:8080/
      SPRING_PROFILES_ACTIVE: docker
      KEYCLOAK_REALM: MsSecurity
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      LOG_LEVEL: INFO
      SERVER_PORT: 8086
      CLIENT_SECRET: 123asd
      CLIENT_ID: user-service
      APPLICATION_NAME: user-service
      CLIENT_RESOURCE_ID: user-client
    ports:
      - "8086:8086"
    restart: on-failure

  account-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_DIR: AccountMS
    image: ghcr.io/heitor-galindo/account-service:4.0.0
    environment:
      EUREKA_HOST: http://eureka:8761/eureka/
      KEYCLOAK_ISSUER: http://keycloak:8080/realms/MsSecurity
      KEYCLOAK_TOKEN_URI: http://keycloak:8080/realms/MsSecurity/protocol/openid-connect/token
      SERVER_PORT: 8084
      APPLICATION_NAME: account-service
      CLIENT_RESOURCE_ID: user-client
      SPRING_PROFILES_ACTIVE: docker
      LOG_LEVEL: INFO
    ports:
      - "8084:8084"
    restart: on-failure

volumes:
  keycloak_data:

