services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.1
    command:
      - start-dev
      - --import-realm
      - --health-enabled=true
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
      # Used when run the services out of docker
#      KC_HOSTNAME: localhost
    #       Used when run the services with docker-compose
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_STRICT: false
      KC_LOG_LEVEL: WARN
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm:/opt/keycloak/data/import
      - keycloak_data:/opt/keycloak/data
    restart: always

  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_DIR: EurekaServer
    image: ghcr.io/heitor-galindo/eureka-server:3.0.0
    ports:
      - "8761:8761"
    restart: on-failure

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_DIR: gateway
    image: ghcr.io/heitor-galindo/gateway:3.0.0
    environment:
      EUREKA_HOST: http://eureka-server:8761/eureka/
      KEYCLOAK_ISSUER: http://keycloak:8080/realms/MsSecurity
      SERVER_PORT: 8089
      SPRING_PROFILES_ACTIVE: docker
      LOG_LEVEL: INFO
    ports:
      - "8089:8089"
    restart: on-failure

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_DIR: StudentMS
    image: ghcr.io/heitor-galindo/user-service:3.0.0
    environment:
      EUREKA_HOST: http://eureka-server:8761/eureka/
      KEYCLOAK_ISSUER: http://keycloak:8080/realms/MsSecurity
      KEYCLOAK_TOKEN_URI: http://keycloak:8080/realms/MsSecurity/protocol/openid-connect/token
      KAFKA_HOST: kafka:29092
      SPRING_PROFILES_ACTIVE: docker
      LOG_LEVEL: INFO
      SERVER_PORT: 8084
    ports:
      - "8084:8084"
    restart: on-failure
    deploy:
      replicas: 2

  account-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_DIR: AccountMS
    image: ghcr.io/heitor-galindo/account-service:3.0.0
    environment:
      EUREKA_HOST: http://eureka-server:8761/eureka/
      KEYCLOAK_ISSUER: http://keycloak:8080/realms/MsSecurity
      KEYCLOAK_TOKEN_URI: http://keycloak:8080/realms/MsSecurity/protocol/openid-connect/token
      USER_CLIENT_SECRET: 123asd
      SERVER_PORT: 8084
      APPLICATION_NAME: accountms
      CLIENT_RESOURCE_ID: user-client
      SPRING_PROFILES_ACTIVE: docker
      LOG_LEVEL: INFO
    ports:
      - "8084:8084"
    restart: on-failure



volumes:
  keycloak_data:
  postgres_data:

